<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<li>The try statement defines a code block to run.</li>

<li> The catch statement defines a code block to handle any error.</li>
 <li>The finally statement defines a code block to run regardless of the result.</li>    
<li> The throw statement defines a custom error.</li>
    <li>Error handling :- </li>
    <ul>
        <li>
            when something happen other than the given condition or task and than error comes is if known as error handling.
        </li>
        <li>
            when something happen other than the given task or expected condition's result comes up in try block which will cause error and that error will be shown in catch block.
        </li>
        
    </ul>


<li>Type Error name:- </li>
<ul>
    <li>
        EvalError =	An error has occurred in the eval() function
    </li>
    <li>   
        RangeError =	A number "out of range" has occurred
    </li> 
    <li>    
        ReferenceError	 =An illegal reference has occurred
    </li>
    <li>    
        SyntaxError = A syntax error has occurred
    </li>
    <li>    
        TypeErrot = A type error has occurred
    </li>
    <li>    
        URIError =	An error in encodeURI() has occurred 
    </li>    
    </li>
</ul>
    <script src ="14d.js"></script>
    
</body>
</html>